/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheIssueRouteImport } from './routes/the-issue'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as QualityEducationRouteImport } from './routes/quality-education'
import { Route as PerspectivesRouteImport } from './routes/perspectives'
import { Route as BeliefsValuesRouteImport } from './routes/beliefs-values'
import { Route as IndexRouteImport } from './routes/index'

const TheIssueRoute = TheIssueRouteImport.update({
  id: '/the-issue',
  path: '/the-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityEducationRoute = QualityEducationRouteImport.update({
  id: '/quality-education',
  path: '/quality-education',
  getParentRoute: () => rootRouteImport,
} as any)
const PerspectivesRoute = PerspectivesRouteImport.update({
  id: '/perspectives',
  path: '/perspectives',
  getParentRoute: () => rootRouteImport,
} as any)
const BeliefsValuesRoute = BeliefsValuesRouteImport.update({
  id: '/beliefs-values',
  path: '/beliefs-values',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beliefs-values': typeof BeliefsValuesRoute
  '/perspectives': typeof PerspectivesRoute
  '/quality-education': typeof QualityEducationRoute
  '/sources': typeof SourcesRoute
  '/the-issue': typeof TheIssueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beliefs-values': typeof BeliefsValuesRoute
  '/perspectives': typeof PerspectivesRoute
  '/quality-education': typeof QualityEducationRoute
  '/sources': typeof SourcesRoute
  '/the-issue': typeof TheIssueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beliefs-values': typeof BeliefsValuesRoute
  '/perspectives': typeof PerspectivesRoute
  '/quality-education': typeof QualityEducationRoute
  '/sources': typeof SourcesRoute
  '/the-issue': typeof TheIssueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beliefs-values'
    | '/perspectives'
    | '/quality-education'
    | '/sources'
    | '/the-issue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beliefs-values'
    | '/perspectives'
    | '/quality-education'
    | '/sources'
    | '/the-issue'
  id:
    | '__root__'
    | '/'
    | '/beliefs-values'
    | '/perspectives'
    | '/quality-education'
    | '/sources'
    | '/the-issue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeliefsValuesRoute: typeof BeliefsValuesRoute
  PerspectivesRoute: typeof PerspectivesRoute
  QualityEducationRoute: typeof QualityEducationRoute
  SourcesRoute: typeof SourcesRoute
  TheIssueRoute: typeof TheIssueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-issue': {
      id: '/the-issue'
      path: '/the-issue'
      fullPath: '/the-issue'
      preLoaderRoute: typeof TheIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-education': {
      id: '/quality-education'
      path: '/quality-education'
      fullPath: '/quality-education'
      preLoaderRoute: typeof QualityEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perspectives': {
      id: '/perspectives'
      path: '/perspectives'
      fullPath: '/perspectives'
      preLoaderRoute: typeof PerspectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beliefs-values': {
      id: '/beliefs-values'
      path: '/beliefs-values'
      fullPath: '/beliefs-values'
      preLoaderRoute: typeof BeliefsValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeliefsValuesRoute: BeliefsValuesRoute,
  PerspectivesRoute: PerspectivesRoute,
  QualityEducationRoute: QualityEducationRoute,
  SourcesRoute: SourcesRoute,
  TheIssueRoute: TheIssueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
