name: Build TSX to HTML

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la
      - name: Show build files
        run: |
          ls -la
          ls -la dist || ls -la build || ls -la out
